
package forms;

import dao.EmprestimoDAO;
import dao.EstudanteDAO;
import dao.LivroDAO;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.Emprestimo;
import model.Estudante;
import model.Livro;

/**
 *
 * @author Willian
 */
public class EmprestimoForm extends javax.swing.JFrame {

    /**
     * Creates new form EmorestimoForm
     */
    public EmprestimoForm() {
        initComponents();
        try {
            emprestimoDAO = new EmprestimoDAO();
            estudanteDAO = new EstudanteDAO();
            livroDAO = new LivroDAO();
        } catch (Exception ex) {
            System.out.println("Deu ruim no construtor");
            Logger.getLogger(EmprestimoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cod_Livro = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        data_Retirada = new javax.swing.JTextField();
        data_Dev = new javax.swing.JTextField();
        data_Ent = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        salvar = new javax.swing.JButton();
        novo = new javax.swing.JButton();
        deletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Código: ");

        jLabel2.setText("Livro:");

        jLabel3.setText("Estudante:");

        jLabel4.setText("Data de Retirada:");

        jLabel5.setText("Data de Devolução:");

        jLabel6.setText("Data de Entrega:");

        jLabel7.setText("Status:");

        cod_Livro.setEnabled(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Livro", "Estudante", "Data de Retirada", "Data de Devolução", "Data de Entrega", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        salvar.setText("salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        novo.setText("novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        deletar.setText("deletar");
        deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cod_Livro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(data_Retirada, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(103, 103, 103))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(179, 179, 179)))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(data_Dev)
                        .addComponent(data_Ent)
                        .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(salvar)
                        .addGap(18, 18, 18)
                        .addComponent(novo)
                        .addGap(27, 27, 27)
                        .addComponent(deletar)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(cod_Livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_Dev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(data_Ent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(data_Retirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salvar)
                    .addComponent(novo)
                    .addComponent(deletar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadComboBox();
        loadTabela();
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();

        cod_Livro.setText((String) jTable1.getValueAt(row, 0));
        try {
            Emprestimo emp = emprestimoDAO.findById(Integer.parseInt((String) jTable1.getValueAt(row, 0)));
            jComboBox1.getModel().setSelectedItem(emp.getLivro());
            jComboBox2.getModel().setSelectedItem(emp.getEstudante());
        } catch (Exception ex) {
            System.out.println("Erro no combo box" + ex.getMessage());
            Logger.getLogger(EmprestimoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        data_Retirada.setText(data_br());
        data_Dev.setText(data_br2());
        data_Ent.setText(data_br3());
        status.setText((String) jTable1.getValueAt(row, 6));
        mode = "UPD";

    }//GEN-LAST:event_jTable1MouseClicked
    public String data_br() {
        int row = jTable1.getSelectedRow();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String data_ret = (String) jTable1.getValueAt(row, 3);
        try {
            data_ret = format.format(emprestimoDAO.findById(Integer.parseInt((String) jTable1.getValueAt(row, 0))).getData_retirada());
        } catch (Exception ex) {
            Logger.getLogger(EmprestimoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return data_ret;
    }

    public String data_br2() {
        int row = jTable1.getSelectedRow();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String data_ret = (String) jTable1.getValueAt(row, 4);
        try {
            data_ret = format.format(emprestimoDAO.findById(Integer.parseInt((String) jTable1.getValueAt(row, 0))).getData_devolucao());
        } catch (Exception ex) {
            Logger.getLogger(EmprestimoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return data_ret;
    }

    public String data_br3() {
        int row = jTable1.getSelectedRow();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String data_ret = (String) jTable1.getValueAt(row, 5);
        try {
            data_ret = format.format(emprestimoDAO.findById(Integer.parseInt((String) jTable1.getValueAt(row, 0))).getData_entrega());
        } catch (Exception ex) {
            Logger.getLogger(EmprestimoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return data_ret;
    }


    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        Emprestimo emp = new Emprestimo();
        try {
            emp.setEmprestimo_id(Integer.parseInt(cod_Livro.getText()));
        } catch (Exception ex) {
            emp.setEmprestimo_id(0);
        }
        emp.setLivro((Livro) jComboBox1.getSelectedItem());
        emp.setEstudante((Estudante) jComboBox2.getSelectedItem());
        emp.setData_devolucao(data_banco(data_Dev.getText()));
        emp.setData_entrega(data_banco(data_Ent.getText()));
        emp.setData_retirada(data_banco(data_Retirada.getText()));
        emp.setLivro((Livro) jComboBox1.getSelectedItem());
        emp.setEstudante((Estudante) jComboBox2.getSelectedItem());
        emp.setStatus(status.getText());

        try {
            if (mode.equals("INS")) {
                emprestimoDAO.save(emp);
            } else if (mode.equals("UPD")) {
                System.out.println("cheguuei");
                emprestimoDAO.update(emp);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex.getMessage());
        }
        loadComboBox();
        loadTabela();
        limparCampos();
    }//GEN-LAST:event_salvarActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        limparCampos();
    }//GEN-LAST:event_novoActionPerformed

    private void deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarActionPerformed
        Emprestimo emp = new Emprestimo();
        try {
            emp.setEmprestimo_id(Integer.parseInt(cod_Livro.getText()));
            emprestimoDAO.delete(emp);
            
        } catch (Exception ex) {
            emp.setEmprestimo_id(0);
        }
        loadTabela();
        loadComboBox();
        limparCampos();
    }//GEN-LAST:event_deletarActionPerformed

    public void limparCampos() {
        cod_Livro.setText("");
        data_Retirada.setText("");
        data_Dev.setText("");
        data_Ent.setText("");
        status.setText("");

        this.mode = "INS";
    }

    public Date data_banco(String data) {
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        try {
            return format.parse(data);
        } catch (Exception ex) {
            Logger.getLogger(EmprestimoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public void loadComboBox() {
        try {
            //PROGRAMAR A BUSCA DE DADOS
            DefaultComboBoxModel model1 = new DefaultComboBoxModel(new Vector(estudanteDAO.findAll()));
            DefaultComboBoxModel model2 = new DefaultComboBoxModel(new Vector(livroDAO.findAll()));
            jComboBox1.setModel(model2);
            jComboBox2.setModel(model1);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void loadTabela() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);

        try {
            for (Emprestimo emp : emprestimoDAO.findAll()) {
                String entrega = (emp.getData_entrega() != null) ? emp.getData_entrega().toString() : "Não entregou";
                String[] row = {
                    "" + emp.getEmprestimo_id(),
                    emp.getLivro().getTitulo(),
                    emp.getEstudante().getNome(),
                    emp.getData_retirada().toString(),
                    emp.getData_devolucao().toString(),
                    entrega,
                    emp.getStatus()
                };
                model.addRow(row);
            }
        } catch (Exception ex) {
            System.out.println("Deu ruim no load table" + ex.getMessage());
            Logger.getLogger(EmprestimoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmprestimoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmprestimoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmprestimoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmprestimoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmprestimoForm().setVisible(true);
            }
        });
    }
    private String mode = "INS";
    private EmprestimoDAO emprestimoDAO;
    private EstudanteDAO estudanteDAO;
    private LivroDAO livroDAO;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cod_Livro;
    private javax.swing.JTextField data_Dev;
    private javax.swing.JTextField data_Ent;
    private javax.swing.JTextField data_Retirada;
    private javax.swing.JButton deletar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton novo;
    private javax.swing.JButton salvar;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}